---
title: "Forms of Redundant Networks"
author: "Abraham Iñiguez"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup:

## Load Packages

```{r message = FALSE}

library("groundhog")
pkgs = c("qgraph", "igraph")
groundhog.library(pkg = pkgs, date = '2026-08-30')
source("00_project_functions.R")
source("RescaleCor.R")

```


### Simulation

```{r}

#### Please change the file path to your preferred location! ####

# Initial values & conditions
nsim = 500
loading = .9

conditions = expand.grid(
  nv = c(10, 20),
  mn.cor = c(0.1, 0.3, 0.5, 0.7, 0.9),
  clone.loading = c(0.7,.9))


ncond = nrow(conditions)
results = vector("list", length = ncond)




start.time = Sys.time()
for (c in 1:ncond){
  nv = conditions$nv[c]
  mn.cor = conditions$mn.cor[c]
  clone.loading = conditions$clone.loading[c]
  
  true.pcor.vals  = vector("list", nsim)
  redun.pcor.vals = vector("list", nsim)
  random.pcor.vals = vector("list", nsim)

# Arrays containing centrality metric data
local.metrics = array(NA, dim = c(nsim, (2*nv + 1), 8),
                 dimnames = list(NULL, c(paste0("P", 1:(nv-1)), "Target", paste0("P", 1:(nv-1), ".r"), "Target.r", "Clone"),  c("Expected Influence","Expected Influence w/o Clone","Strength", "Strength w/o Clone", "Closeness","Closeness w/o Clone", "Betweenness", "Betweenness w/o Clone")))

global.metrics = array(NA, dim = c(nsim, 3, 2),
                       dimnames = list(NULL, c("True Network",
                                               "Redundant Network", 
                                               "Redundant Network w/o Clone"),
                                       c("APL", "Weighted Density")))


local.metrics.random = array(NA, dim = c(nsim, (2*nv + 1), 8),
                 dimnames = list(NULL, c(paste0("P", 1:(nv-1)), "Target", paste0("P", 1:(nv-1), ".r"), "Target.r", "Random"),  c("Expected Influence","Expected Influence w/o Random","Strength", "Strength w/o Random", "Closeness","Closeness w/o Random", "Betweenness", "Betweenness w/o Random")))

global.metrics.random = array(NA, dim = c(nsim, 3, 2),
                       dimnames = list(NULL, c("True Network",
                                               "Random Network",
                                               "Random Network w/o Random"),
                                       c("APL", "Weighted Density")))



flag = 0

for (i in 1:nsim){
  
lat.corr.full = cor.gen(nvar = nv + 1, mn.cor = mn.cor)
lat.corr = lat.corr.full[1:nv, 1:nv]
  
  if(flag == 0){

  
# Correlation matrix of the indicators with the inclusion of the additional random indicator
  random.corr = ind.corr(matrix = lat.corr.full,
                         loadings = loading,
                         clone.loading = clone.loading,
                         redundancy = FALSE)

# Correlation matrix of the indicators excluding the additional random indicator
  true.corr = random.corr[1:nv, 1:nv]

# Partial correlation matrix of the indicators excluding the additional random indicator
  true.pcor = cor2pcor(true.corr)
  colnames(true.pcor) = c(paste0("P", 1:(nv-1)), "Target")
# Partial correlation matrix of the indicators with the inclusion of the random indicator
  random.pcor = cor2pcor(random.corr)
  colnames(random.pcor) = c(paste0("P", 1:(nv-1), ".r"), "Target.r", "Random")
  random.pcor.vals[[i]] <- random.pcor[lower.tri(random.pcor)]


# Create a block for easier centrality computation 
  one = cbind(true.pcor, diag(0, nv, nv+1))
  two = cbind(diag(0, nv+1, nv), random.pcor)
  the.g = rbind(one, two)
  colnames(the.g)[(nv+1):((2*nv)+1)] = c(paste0("P", 1:(nv-1), ".r"), "Target.r", "Random")
  the.g = graph_from_adjacency_matrix(the.g,
                                       mode = "undirected",
                                       weighted = TRUE)
  tpcor.graph = graph_from_adjacency_matrix(true.pcor,
                                            mode = "undirected",
                                            weighted = TRUE)
  randompcor.graph = graph_from_adjacency_matrix(random.pcor,
                                                 mode = "undirected",
                                                 weighted = TRUE)

  randompcor.graph.wo.random =  delete_vertices(randompcor.graph,
                                                "Random")

## Centrality metrics 

# Local metrics

# Full random network(EI)
  local.metrics.random[i,, "Expected Influence"] = strength(the.g)
  
# "Additional" node exclusion in random network (EI)
  node.ei = strength(the.g)
  random.cnx.ei = E(the.g)$weight[which(grepl(pattern = "Random",
                                               x = as_ids(E(the.g))))]
  node.ei[(nv+1):(2*nv)] = (node.ei[(nv+1):(2*nv)]-random.cnx.ei)
  local.metrics.random[i,,"Expected Influence w/o Random"] = node.ei
  
# Full random network(S)
  local.metrics.random[i,,"Strength"] = strength(the.g,
                                                  weights = abs(E(the.g)$weight))
# "Additional" node exclusion in random network(S)
  node.s = strength(the.g, weights = abs(E(the.g)$weight))
  random.cnx.s = abs(E(the.g)$weight[which(grepl(pattern = "Random",
                                                  x = as_ids(E(the.g))))])
  node.s[(nv+1):(2*nv)] = (node.s[(nv+1):(2*nv)]-random.cnx.s)
  local.metrics.random[i,,"Strength w/o Random"] = node.s
  
# Full random network(C)  
  local.metrics.random[i,,"Closeness"] = closeness(the.g, weights = 1/round(abs(E(the.g)$weight),2), normalized = TRUE)
  
# "Additional" node exclusion in random network(C)
  
# Remove "additional" node from random network
  g.wo.random = delete_vertices(the.g,
                                 "Random")
# Compute closeness of nodes without "additional" node
  node.wo.c = closeness(g.wo.random,
                         normalized = TRUE,
                         weights = 1/round(abs(E(g.wo.random)$weight), 2))
# Compute the closeness on the.g. This lets us obtain each node's closeness value across true and random network
  node.c = closeness(the.g,
                    normalized = TRUE,
                    weights = 1/abs(E(the.g)$weight))
# In node.c, replace closeness values from node.wo.c with all nodes in the random network except the "additional" node
  node.c[1:(2*nv)] = node.wo.c
# Save node.c for every observation of "Closeness w/o Random"
  local.metrics.random[i,,"Closeness w/o Random"] = node.c
  
# Full random network(B)
  local.metrics.random[i,,"Betweenness"] = betweenness(the.g, weights = 1/(abs(E(the.g)$weight)),
                                                        normalized = TRUE)
# "Additional" node exclusion in random network(B)
  node.wo.b = betweenness(g.wo.random,
                           normalized = TRUE,
                           weights = 1/abs(E(g.wo.random)$weight))
  node.b = betweenness(the.g,
                        normalized = TRUE,
                        weights = 1/abs(E(the.g)$weight)) 
  node.b[1:(2*nv)] = node.wo.b
  local.metrics.random[i,,"Betweenness w/o Random"] = node.b
  

## Global metrics  
  global.metrics.random[i,"True Network","APL"] = mean_distance(tpcor.graph,
                                                                 weights = 1/abs(E(tpcor.graph)$weight))
  global.metrics.random[i, "Random Network", "APL"] = mean_distance(randompcor.graph,
                                                                     weights = 1/abs(E(randompcor.graph)$weight))
  global.metrics.random[i, "Random Network w/o Random", "APL"] = mean_distance(randompcor.graph.wo.random,
weights = 1/abs(E(randompcor.graph.wo.random)$weight))
  global.metrics.random[i, "True Network", "Weighted Density"] = weighted.density(igrph.object = tpcor.graph,
                                                                                   abs = TRUE)
  global.metrics.random[i, "Random Network", "Weighted Density"] = weighted.density(igrph.object = randompcor.graph,
                                                                                     abs = TRUE)
  global.metrics.random[i,"Random Network w/o Random", "Weighted Density"] = weighted.density(igrph.object = randompcor.graph.wo.random,
                                                                                               abs = TRUE)
  
}

  
# Correlation matrix of the indicators with the inclusion of the redundant indicator
  redun.corr = ind.corr(matrix = lat.corr,
                         loadings = loading,
                         clone.loading = clone.loading,
                         redundancy = TRUE)
 
# Correlation matrix of the indicators excluding the redundant indicator
  true.corr = redun.corr[1:nv, 1:nv]

# Partial correlation matrix of the indicators excluding the redundant indicator
  true.pcor = cor2pcor(true.corr)
  colnames(true.pcor) = c(paste0("P", 1:(nv-1)), "Target")
  true.pcor.vals[[i]] <- true.pcor[lower.tri(true.pcor)]
# Partial correlation matrix of the indicators including the redundant indicator
  redun.pcor = cor2pcor(redun.corr)
  colnames(redun.pcor) = c(paste0("P", 1:(nv-1), ".r"), "Target.r", "Clone")
  redun.pcor.vals[[i]] <- redun.pcor[lower.tri(redun.pcor)]


# Create a block for easier centrality computation 
  one = cbind(true.pcor, diag(0, nv, nv+1))
  two = cbind(diag(0, nv+1, nv), redun.pcor)
  the.g = rbind(one, two)
  colnames(the.g)[(nv+1):((2*nv)+1)] = c(paste0("P", 1:(nv-1), ".r"),
                                         "Target.r",
                                         "Clone")
  the.g = graph_from_adjacency_matrix(the.g,
                                       mode = "undirected",
                                       weighted = TRUE)
  tpcor.graph = graph_from_adjacency_matrix(true.pcor,
                                            mode = "undirected",
                                            weighted = TRUE)
  rpcor.graph = graph_from_adjacency_matrix(redun.pcor,
                                            mode = "undirected",
                                            weighted = TRUE)
  rpcor.graph.wo.clone =  delete_vertices(rpcor.graph,
                                          "Clone")
  

## Centrality metrics 

# Local metrics
# Full redundant network(EI)
  local.metrics[i,, "Expected Influence"] = strength(the.g)
  
# Clone exclusion in redundant network(EI)
  node.ei = strength(the.g)
  clone.cnx.ei = E(the.g)$weight[which(grepl(pattern = "Clone",
                                              x = as_ids(E(the.g))))]
  node.ei[(nv+1):(2*nv)] = (node.ei[(nv+1):(2*nv)]-clone.cnx.ei)
  local.metrics[i,,"Expected Influence w/o Clone"] = node.ei
  
# Full redundant network(S)
  local.metrics[i,,"Strength"] = strength(the.g,
                                           weights = abs(E(the.g)$weight))
  
# Clone exclusion in redundant network(S)
  node.s = strength(the.g, weights = abs(E(the.g)$weight))
  clone.cnx.s = abs(E(the.g)$weight[which(grepl(pattern = "Clone",
                                                 x = as_ids(E(the.g))))])
  node.s[(nv+1):(2*nv)] = (node.s[(nv+1):(2*nv)]-clone.cnx.s)
  local.metrics[i,,"Strength w/o Clone"] = node.s
  
# Full redundant network(C)  
  local.metrics[i,,"Closeness"] = closeness(the.g,
                                             weights = 1/round(abs(E(the.g)$weight),2),
                                             normalized = TRUE)
  
# Clone exclusion in redundant network(C)
  g.wo.clone = delete_vertices(the.g,
                                "Clone")
  node.wo.c = closeness(g.wo.clone, normalized = TRUE,
                         weights = 1/round(abs(E(g.wo.clone)$weight), 2))
  node.c = closeness(the.g,
                      normalized = TRUE,
                      weights = 1/abs(E(the.g)$weight))
  node.c[1:(2*nv)] = node.wo.c
  local.metrics[i,,"Closeness w/o Clone"] = node.c

# Full redundant network(B)
  local.metrics[i,,"Betweenness"] = betweenness(the.g,
                                                 weights =1/(abs(E(the.g)$weight)),
                                                 normalized = TRUE)
# Clone exclusion in redundant network(B)
  node.wo.b = betweenness(g.wo.clone,
                           normalized = TRUE,
                           weights = 1/abs(E(g.wo.clone)$weight))
  node.b = betweenness(the.g,
                       normalized = TRUE,
                       weights = 1/abs(E(the.g)$weight))

  node.b[1:(2*nv)] = node.wo.b
  local.metrics[i,,"Betweenness w/o Clone"] = node.b
  
## Global metrics  
  global.metrics[i,"True Network","APL"] = mean_distance(tpcor.graph, weights = 1/abs(E(tpcor.graph)$weight))
  global.metrics[i, "Redundant Network", "APL"] = mean_distance(rpcor.graph, weights = 1/abs(E(rpcor.graph)$weight))
  global.metrics[i, "Redundant Network w/o Clone", "APL"] = mean_distance(rpcor.graph.wo.clone,
weights = 1/abs(E(rpcor.graph.wo.clone)$weight))
  global.metrics[i, "True Network", "Weighted Density"] = weighted.density(igrph.object = tpcor.graph,
                                                                            abs = TRUE)
  global.metrics[i, "Redundant Network", "Weighted Density"] = weighted.density(igrph.object = rpcor.graph,
                                                                                 abs = TRUE)
  global.metrics[i,"Redundant Network w/o Clone", "Weighted Density"] = weighted.density(igrph.object = rpcor.graph.wo.clone, abs = TRUE)
}

 results[[c]] = list(
   condition = conditions[c, ],
   local.metrics = local.metrics,
   global.metrics = global.metrics,
   local.metrics.random = local.metrics.random,
   global.metrics.random = global.metrics.random,
   true.pcor = true.pcor.vals,
   redun.pcor = redun.pcor.vals,
   random.pcor = random.pcor.vals
  )
 

    saveRDS(object = results, 
           file = "/Users/aginigue/Library/CloudStorage/Box-Box/Redundancy_Project/Simulation/simulation_resultsP1.rds")

}
end.time = Sys.time()
time.taken = end.time - start.time
print(time.taken)
xfun::session_info()

```

