---
title: "Forms of Redundant Networks"
author: "Abraham Iñiguez"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Network Test & Setup:

## Load Packages

```{r message = FALSE}
library(qgraph)
library(igraph)
source("00_project_functions.R")
```

### Main Simulation


```{r}
# Initialize input values
nsim <- 10
nv <- 4
ep <- .9
EF <- .5

```

```{r echo = FALSE}
# Functions needed
# corr_gen() ~ Obtain true network corr matrix
# cor2pcor() ~ Move from corr matrix to pcor matrix



#  contains the full simulated data

hcsf_all <- array(NA, dim = c(nsim, (2*nv + 1), 3),
                 dimnames = list(NULL, c(paste0("P", 1:(nv-1)), "Target", paste0("P", 1:(nv-1), ".r"), "Target.r", "Clone"), c("strength", "closeness", "betweenness")))


hcsf_wc <- array(NA, dim = c(nsim, nv, 3),
                  dimnames = list(NULL, c(paste0("P", 1:(nv-1)), "Target"), c("strength", "closeness", "betweenness")))
head(hcsf_all)
head(hcsf_wc)


for (i in 1:nsim){
  true_mat <- corr_gen(nv = nv, EF = EF, edge.probability = ep)
  redun_mat <- hcsf(matrix = true_mat)
  true_subset <- redun_mat[1:nv, 1:nv]
  true_pcor_subset <- cor2pcor(true_subset)
  redun_pcor <- cor2pcor(redun_mat)
# Create one block matrix for easy computation
  one <- cbind(true_pcor_subset, diag(0, nv, nv+1))
  two <- cbind(diag(0, nv+1, nv), redun_pcor)
  the_g <- rbind(one, two)
  colnames(the_g) <- c(paste0("P", 1:(nv-1)), "Target", paste0("P", 1:(nv-1), ".r"), "Target.r", "Clone")
  
# qgraph plots and graph matrices
  g1 = qgraph(true_pcor_subset, edge.labels = TRUE, DoNotPlot = TRUE)
  if (i == 1){
  g2 = qgraph(redun_pcor, edge.labels = TRUE, DoNotPlot = TRUE)
  pp = averageLayout(g2)}
  png(filename = paste0('/Users/abraham/Library/CloudStorage/Box/Redundancy_Project/R/Network Graphs/HCSF_Graph_', i, ".png"), width = 1000, height = 500)
  par(mfrow = c(1, 2))
  g1 = qgraph(true_pcor_subset, layout = pp[1:nv,], edge.labels = TRUE, theme = "colorblind", labels = colnames(the_g)[1:nv], maximum = 1, vsize = 11)
  g2 = qgraph(redun_pcor,layout = pp, edge.labels = TRUE, theme = "colorblind", labels = colnames(the_g)[(nv+1):(2*nv + 1)], maximum = 1, vsize = 11)
  graphics.off()
  the_g <- graph_from_adjacency_matrix(the_g, mode = "undirected", weighted = TRUE)
  saveRDS(the_g, paste0('/Users/abraham/Library/CloudStorage/Box/Redundancy_Project/R/Graph Matrices/HCSF_File_', i, ".RDS"))
  
#Compute Strength, Closeness, and Betweenness    
  hcsf_all[i,, "strength"] <- strength(the_g)
  hcsf_all[i,,"closeness"] <- closeness(the_g, weights = 1/round(abs(E(the_g)$weight),2), normalized = TRUE)
  hcsf_all[i,,"betweenness"] <- betweenness(the_g, weights = 1/(abs(E(the_g)$weight)), normalized = FALSE)

  if (!is.null(hcsf_all)) {
  saveRDS(hcsf_all, paste0('/Users/abraham/Library/CloudStorage/Box/Redundancy_Project/R/Metrics/HCSF_', i , ".RDS"))
  prev_file <- paste0('/Users/abraham/Library/CloudStorage/Box/Redundancy_Project/R/Metrics/HCSF_', i - 1, ".RDS")
  if (file.exists(prev_file)) {
    file.remove(prev_file)
  }

} else {
  message(paste0("Ope, this run had an error. Preserving simulation as of Replication ", i))
}
  
# Compute clone exclusion difference in redundancy network
  total_strength <- strength(the_g)
  connections_2_clone <- E(the_g)$weight[which(grepl("Clone", as_ids(E(the_g))))]
  hcsf_wc[i,,"strength"] <- (total_strength[(nv+1):(2*nv)] - connections_2_clone) - total_strength[1:nv]
  
  clone_edges <- E(the_g)[grepl("Clone", as_ids(E(the_g)))]
  g_no_clone <- delete_edges(the_g, clone_edges)
  closeness_wc <- closeness(g_no_clone, normalized = TRUE, weights = 1/abs(E(g_no_clone)$weight))
  closeness_wthc <- closeness(the_g, normalized = TRUE, weights = 1/abs(E(the_g)$weight))
  hcsf_wc[i,,"closeness"] <- closeness_wc[(nv+1):(2*nv)] - closeness_wthc[1:nv]
  
 betweenness_wc <- betweenness(g_no_clone, normalized = FALSE, weights = 1/abs(E(g_no_clone)$weight))
 betweenness_wthc <- betweenness(the_g, normalized = FALSE,  weights = 1/abs(E(the_g)$weight))
 hcsf_wc[i,,"betweenness" ] <- betweenness_wc[(nv+1):(2*nv)] - betweenness_wthc[1:nv]

}
```

### Test Simulation

```{r}
# Initial values 
nsim <- 1000
nv <- 4
ep <- .9
EF <- .5
loading <- .9


# Arrays containing centrality metric data
local_metrics <- array(NA, dim = c(nsim, (2*nv + 1), 8),
                 dimnames = list(NULL, c(paste0("P", 1:(nv-1)), "Target", paste0("P", 1:(nv-1), ".r"), "Target.r", "Clone"),  c("Expected Influence","Expected Influence w/o Clone","Strength", "Strength w/o Clone", "Closeness","Closeness w/o Clone", "Betweenness", "Betweenness w/o Clone")))

global_metrics = array(NA, dim = c(nsim, 3, 2),
                       dimnames = list(NULL, c("True Network",
                                               "Redundant Network", 
                                               "Redundant Network w/o Clone"),
                                       c("APL", "Weighted Density")))


local_metrics_random <- array(NA, dim = c(nsim, (2*nv + 1), 8),
                 dimnames = list(NULL, c(paste0("P", 1:(nv-1)), "Target", paste0("P", 1:(nv-1), ".r"), "Target.r", "Random"),  c("Expected Influence","Expected Influence w/o Random","Strength", "Strength w/o Random", "Closeness","Closeness w/o Random", "Betweenness", "Betweenness w/o Random")))

global_metrics_random = array(NA, dim = c(nsim, 3, 2),
                       dimnames = list(NULL, c("True Network",
                                               "Random Network",
                                               "Random Network w/o Random"),
                                       c("APL", "Weighted Density")))


flag = 0
for (i in 1:nsim){if(flag == 0){
# Correlation matrix of the latent variables
  lat_corr <- corr_gen(nv = nv, EF = EF, edge.probability = ep)
  
# Correlation matrix of the indicators with the inclusion of the additional random indicator
  random_corr <- ind_corr(matrix = lat_corr,
                         loadings = loading,
                         redundancy = FALSE)

# Correlation matrix of the indicators excluding the additional random indicator
  true_corr <- random_corr[1:nv, 1:nv]

# Partial correlation matrix of the indicators excluding the additional random indicator
  true_pcor <- cor2pcor(true_corr)
  colnames(true_pcor) = c(paste0("P", 1:(nv-1)), "Target")
# Partial correlation matrix of the indicators with the inclusion of the random indicator
  random_pcor <- cor2pcor(random_corr)
  colnames(random_pcor) = c(paste0("P", 1:(nv-1), ".r"), "Target.r", "Random")


# Create a block for easier centrality computation 
  one <- cbind(true_pcor, diag(0, nv, nv+1))
  two <- cbind(diag(0, nv+1, nv), random_pcor)
  the_g <- rbind(one, two)
  colnames(the_g)[(nv+1):((2*nv)+1)] = c(paste0("P", 1:(nv-1), ".r"), "Target.r", "Random")
  the_g <- graph_from_adjacency_matrix(the_g,
                                       mode = "undirected",
                                       weighted = TRUE)
  tpcor_graph = graph_from_adjacency_matrix(true_pcor,
                                            mode = "undirected",
                                            weighted = TRUE)
  randompcor_graph = graph_from_adjacency_matrix(random_pcor,
                                                 mode = "undirected",
                                                 weighted = TRUE)
  random.cnx.wa =  E(randompcor_graph)[grepl("Random",
                                             as_ids(E(randompcor_graph)))]
  randompcor_graph_wo_random =  delete_vertices(randompcor_graph,
                                                "Random")
  

## Centrality metrics 

# Local metrics

# Full random network(EI)
  local_metrics_random[i,, "Expected Influence"] <- strength(the_g)
  
# "Additional" node exclusion in random network (EI)
  node.ei <- strength(the_g)
  random.cnx.ei <- E(the_g)$weight[which(grepl(pattern = "Random",
                                               x = as_ids(E(the_g))))]
  node.ei[(nv+1):(2*nv)] <- (node.ei[(nv+1):(2*nv)]-random.cnx.ei)
  local_metrics_random[i,,"Expected Influence w/o Random"] <- node.ei
  
# Full random network(S)
  local_metrics_random[i,,"Strength"] <- strength(the_g,
                                                  weights = abs(E(the_g)$weight))
# "Additional" node exclusion in random network(S)
  node.s <- strength(the_g, weights = abs(E(the_g)$weight))
  random.cnx.s <- abs(E(the_g)$weight[which(grepl(pattern = "Random",
                                                  x = as_ids(E(the_g))))])
  node.s[(nv+1):(2*nv)] <- (node.s[(nv+1):(2*nv)]-random.cnx.s)
  local_metrics_random[i,,"Strength w/o Random"] <- node.s
  
# Full random network(C)  
  local_metrics_random[i,,"Closeness"] <- closeness(the_g, weights = 1/round(abs(E(the_g)$weight),2), normalized = TRUE)
  
# "Additional" node exclusion in random network(C)
  
# Remove "additional" node from random network
  g.wo.random <- delete_vertices(the_g,
                                 "Random")
# Compute closeness of nodes without "additional" node
  node.wo.c <- closeness(g.wo.random,
                         normalized = TRUE,
                         weights = 1/abs(E(g.wo.random)$weight))
# Compute the closeness on the_g. This lets us obtain each node's closeness value across true and random network
  node.c <- closeness(the_g,
                    normalized = TRUE,
                    weights = 1/abs(E(the_g)$weight))
# In node.c, replace closeness values from node.wo.c with all nodes in the random network except the "additional" node
  node.c[1:8] = node.wo.c
# Save node.c for every observation of "Closeness w/o Random"
  local_metrics_random[i,,"Closeness w/o Random"] <- node.c
  
# Full random network(B)
  local_metrics_random[i,,"Betweenness"] <- betweenness(the_g, weights = 1/(abs(E(the_g)$weight)),
                                                        normalized = FALSE)
# "Additional" node exclusion in random network(B)
  node.wo.b <- betweenness(g.wo.random,
                           normalized = FALSE,
                           weights = 1/abs(E(g.wo.random)$weight))
  node.b <- betweenness(the_g,
                        normalized = FALSE,
                        weights = 1/abs(E(the_g)$weight)) 
  node.b[1:8] = node.wo.b
  local_metrics_random[i,,"Betweenness w/o Random"] <- node.b
  

## Global metrics  
  global_metrics_random[i,"True Network","APL"] <- mean_distance(tpcor_graph,
                                                                 weights = 1/abs(E(tpcor_graph)$weight))
  global_metrics_random[i, "Random Network", "APL"] <- mean_distance(randompcor_graph,
                                                                     weights = 1/abs(E(randompcor_graph)$weight))
  global_metrics_random[i, "Random Network w/o Random", "APL"] <- mean_distance(randompcor_graph_wo_random,
weights = 1/abs(E(randompcor_graph_wo_random)$weight))
  global_metrics_random[i, "True Network", "Weighted Density"] <- weighted_density(igrph.object = tpcor_graph,
                                                                                   abs = TRUE)
  global_metrics_random[i, "Random Network", "Weighted Density"] <- weighted_density(igrph.object = randompcor_graph,
                                                                                     abs = TRUE)
  global_metrics_random[i,"Random Network w/o Random", "Weighted Density"] <- weighted_density(igrph.object = randompcor_graph_wo_random,
                                                                                               abs = TRUE)
  
}
# Correlation matrix of the latent variables
  lat_corr <- corr_gen(nv = nv, EF = EF, edge.probability = ep)
  
# Correlation matrix of the indicators with the inclusion of the redundant indicator
  redun_corr <- ind_corr(matrix = lat_corr,
                         loadings = loading,
                         clone_loading = .9,
                         redundancy = TRUE)
 
# Correlation matrix of the indicators excluding the redundant indicator
  true_corr <- redun_corr[1:nv, 1:nv]

# Partial correlation matrix of the indicators excluding the redundant indicator
  true_pcor <- cor2pcor(true_corr)
  colnames(true_pcor) = c(paste0("P", 1:(nv-1)), "Target")
# Partial correlation matrix of the indicators including the redundant indicator
  redun_pcor <- cor2pcor(redun_corr)
  colnames(redun_pcor) = c(paste0("P", 1:(nv-1), ".r"), "Target.r", "Clone")


# Create a block for easier centrality computation 
  one <- cbind(true_pcor, diag(0, nv, nv+1))
  two <- cbind(diag(0, nv+1, nv), redun_pcor)
  the_g <- rbind(one, two)
  colnames(the_g)[(nv+1):((2*nv)+1)] = c(paste0("P", 1:(nv-1), ".r"),
                                         "Target.r",
                                         "Clone")
  the_g <- graph_from_adjacency_matrix(the_g,
                                       mode = "undirected",
                                       weighted = TRUE)
  tpcor_graph = graph_from_adjacency_matrix(true_pcor,
                                            mode = "undirected",
                                            weighted = TRUE)
  rpcor_graph = graph_from_adjacency_matrix(redun_pcor,
                                            mode = "undirected",
                                            weighted = TRUE)
  rpcor_graph_wo_clone =  delete_vertices(rpcor_graph,
                                          "Clone")
  

## Centrality metrics 

# Local metrics
# Full redundant network(EI)
  local_metrics[i,, "Expected Influence"] <- strength(the_g)
  
# Clone exclusion in redundant network(EI)
  node.ei <- strength(the_g)
  clone.cnx.ei <- E(the_g)$weight[which(grepl(pattern = "Clone",
                                              x = as_ids(E(the_g))))]
  node.ei[(nv+1):(2*nv)] <- (node.ei[(nv+1):(2*nv)]-clone.cnx.ei)
  local_metrics[i,,"Expected Influence w/o Clone"] <- node.ei
  
# Full redundant network(S)
  local_metrics[i,,"Strength"] <- strength(the_g,
                                           weights = abs(E(the_g)$weight))
  
# Clone exclusion in redundant network(S)
  node.s <- strength(the_g, weights = abs(E(the_g)$weight))
  clone.cnx.s <- abs(E(the_g)$weight[which(grepl(pattern = "Clone",
                                                 x = as_ids(E(the_g))))])
  node.s[(nv+1):(2*nv)] <- (node.s[(nv+1):(2*nv)]-clone.cnx.s)
  local_metrics[i,,"Strength w/o Clone"] <- node.s
  
# Full redundant network(C)  
  local_metrics[i,,"Closeness"] <- closeness(the_g,
                                             weights = 1/round(abs(E(the_g)$weight),2),
                                             normalized = TRUE)
  
# Clone exclusion in redundant network(C)
  g.wo.clone <- delete_vertices(the_g,
                                "Clone")
  node.wo.c <- closeness(g.wo.clone, normalized = TRUE,
                         weights = 1/abs(E(g.wo.clone)$weight))
  node.c = closeness(the_g,
                      normalized = TRUE,
                      weights = 1/abs(E(the_g)$weight))
  node.c[1:8] = node.wo.c
  local_metrics[i,,"Closeness w/o Clone"] <- node.c

# Full redundant network(B)
  local_metrics[i,,"Betweenness"] <- betweenness(the_g,
                                                 weights =1/(abs(E(the_g)$weight)),
                                                 normalized = FALSE)
# Clone exclusion in redundant network(B)
  node.wo.b <- betweenness(g.wo.clone,
                           normalized = FALSE,
                           weights = 1/abs(E(g.wo.clone)$weight))
  node.b = betweenness(the_g,
                       normalized = FALSE,
                       weights = 1/abs(E(the_g)$weight))
  node.b[1:8] = node.wo.b
  local_metrics[i,,"Betweenness w/o Clone"] <- node.b
  
## Global metrics  
  global_metrics[i,"True Network","APL"] <- mean_distance(tpcor_graph, weights = 1/abs(E(tpcor_graph)$weight))
  global_metrics[i, "Redundant Network", "APL"] <- mean_distance(rpcor_graph, weights = 1/abs(E(rpcor_graph)$weight))
  global_metrics[i, "Redundant Network w/o Clone", "APL"] <- mean_distance(rpcor_graph_wo_clone,
weights = 1/abs(E(rpcor_graph_wo_clone)$weight))
  global_metrics[i, "True Network", "Weighted Density"] <- weighted_density(igrph.object = tpcor_graph,
                                                                            abs = TRUE)
  global_metrics[i, "Redundant Network", "Weighted Density"] <- weighted_density(igrph.object = rpcor_graph,
                                                                                 abs = TRUE)
  global_metrics[i,"Redundant Network w/o Clone", "Weighted Density"] <- weighted_density(igrph.object = rpcor_graph_wo_clone, abs = TRUE)
}




```




### Tasks

1) Integrate conditions
2) Curious to test: if sample size is increased, will difference in closeness values between nodes change in the redundant/random network?







